server:
  port: 8888
spring:
  application:
    name: foo-config-server
    
  profiles:
    active:
      - native

#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/felipeechagas/config-Server.git
#          #username: username
#          #password: password